[build]
  base = "./"
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cross-Origin-Embedder-Policy = 'require-corp; report-to="default";'
    Cross-Origin-Opener-Policy = 'same-site; report-to="default";'
    Cross-Origin-Resource-Policy = "same-site"
    Permissions-Policy = "self"

[[edge_functions]]
  path = "/banner"
  function = "banner"
